using System.Reflection;
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
 
[assembly: AssemblyProduct("LS Commerce Service")] 
[assembly: AssemblyCompany("LS Retail")]
[assembly: AssemblyCopyright("Copyright 2021 LS Retail")]
[assembly: AssemblyTrademark("LS Retail")]
[assembly: AssemblyCulture("")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
[assembly: AssemblyVersion("4.21.0")]
[assembly: AssemblyFileVersion("4.21.0")]
[assembly: AssemblyInformationalVersion("LS Commerce Service 4.21")]
 